version: "2"
run:
  tests: true
  allow-parallel-runners: true
linters:
  default: none
  enable:
    - copyloopvar
    - dogsled
    - errcheck
    - errorlint
    - goconst
    - gocritic
    - gosec
    - govet
    - ineffassign
    - misspell
    - nakedret
    - nolintlint
    - revive
    - staticcheck
    - thelper
    - unconvert
    - unused